import type { Metadata } from "next";
import { Chewy, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GameProvider } from "../context/GameContext";
import { ThirdwebProvider } from "thirdweb/react";


const chewy = Chewy({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "GOOZ-Dot-Fun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${chewy.variable} antialiased`}
      >
        <ThirdwebProvider>
          <GameProvider>
            {children}
          </GameProvider>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
