import type { Metadata } from "next";
import { Chewy, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@near-wallet-selector/modal-ui/styles.css"
import { WalletProvider } from "@/context/WalletProvider";
import { GameProvider } from "../context/GameContext";


const chewy = Chewy({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <WalletProvider>
      <GameProvider>
        <html lang="en">
          <body
            className={`${chewy.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </GameProvider>
    </WalletProvider>
  );
}
